/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex gap-40 justify-between items-center text-xs py-4 px-10 w-full">
          <img className="w-[52px]" src="/test1.svg" alt="Logo" />
          <div className="flex gap-3.5 justify-between whitespace-nowrap text-sm font-light">
            <a href="#about">About</a>
            <a href="#career">Career</a>
            <a href="#contact">Contact</a>
          </div>
        </header>
        {children}
        {/* <footer className="flex flex-col gap-2 p-4 w-full items-center">
          <div className="flex gap-4">
            <p>LinkedIn</p>
            <p>GitHub</p>
            <p>Email</p>
          </div>
          <p>© {new Date().getFullYear()} Nicolas Andreoli</p>
        </footer> */}
      </body>
    </html>
  );
}
